---
title: "Oak Data Exploration"
author: "Jessica M Zamudio"
format: html
editor: visual
---

```{r}
install.packages("tidyverse")
library(tidyverse)

library(readxl)

Survival_HeightApril26Blocks7_6Clean <- read_excel("Oak Project/Data/Survival_HeightApril26Blocks7&6Clean.xlsx", 
                                                   sheet = "Input1", skip = 1)
View(Survival_HeightApril26Blocks7_6Clean)

names(Survival_HeightApril26Blocks7_6Clean)

```

```{r}
Survival_HeightApril26Blocks7_6Clean <-
  Survival_HeightApril26Blocks7_6Clean |> 
  rename(Page_Num ="Page #",
         Date ="MM/DD/YYYY", 
        Recorder ="Name",
       Block  ="#...4",
      Tag_Num   ="#...5",
       Oak_type  ="NR, S, or A",
        Treatment ="AC, OA, NP, DT, or DL",
     OA_microclimate    ="TH, TI, CN",
       Seedling_Ht_cm  ="(cm)",
        Num_leaves ="#...10",
       Num_dead_leaves  ="#...11",
        Leaf_greenness ="%",
        Num_germinated ="#...13",
       RCD  = "(mm)",
       Notes  ="as written on data sheet"
         )
```

The `echo: false` option disables the printing of code (only output is displayed).
